version: 2
jobs:
  build:
    docker:
      - image: silex/emacs:26.2
    steps:
      - checkout
      - run: emacs --version
      # /bin/bash: make: command not found
      # - run: make compile
      - run: emacs -Q --batch -L . --eval "(setq byte-compile-error-on-warn t)" -f batch-byte-compile baidu-fanyi.el
